# Generated by Django 2.0.3 on 2018-04-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homepage',
            new_name='businessCard',
        ),
    ]
