# Generated by Django 2.0.3 on 2018-04-13 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180413_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
